name: Loan_prediction
chanels:
  -defaults

dependencies:
  - python=3.12.2
  - pip<=25.0.1
  - pip:
    - mlflow==2.22.0
    - cloudpickle==3.0.0
    - numpy==1.26.4
    - pandas==2.2.3
    - psutil==6.0.0
    - scikit-learn==1.6.1
    - scipy==1.14.1
    - typing==3.7.4.3